test/uploadVideo.js

(PR | ISSUE) : [CD-19]
* AWS-SDK 라이브러리를 사용하여 특정 S3 버킷에 영상 업로드
* 형식: {사용자이름}/{파일이름}
- 작업 예정
```node uploadVideo.js``` 로 실행
* 동영상이 해당 프로젝트 폴더 내에 있어야 함
- 질문
[CD-19]: https://cd-carpe-diem.atlassian.net/browse/CD-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: S3 비디오 업로드

---

src/api/card.ts
src/app.ts
src/common/constant/responseMessage.ts
src/services/card.ts

(PR | ISSUE) : [CD-24]
- Request URL : GET `/card`
- Request header user Id 포함해야해요~!
- 작업 예정
- 핵심 내용
- 질문
[CD-22]: https://cd-carpe-diem.atlassian.net/browse/CD-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-24]: https://cd-carpe-diem.atlassian.net/browse/CD-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 카드 리스트 GET API

---

src/api/card.ts
src/services/card.ts

(PR | ISSUE) : #8 
- 비디오 뷰) 전체 카드 띄우는 부분 service 로직 네이밍하고 request 형식 변경했습니다.
- 기존 header로 전달 -> path parameter 방식으로 변경
- 나중에 auth 구현되면 userId 노출되는 거 지울 예정입니다.
- 핵심 내용
- 질문

Fix: get cards API request 변경

---

src/api/card.ts
src/services/card.ts

(PR | ISSUE) : #8 #9  [CD-84]
- 단일 카드 페이지 GET API 추가
- 단일 페이지 삭제 API 추가
- 단일 페이지 수정 API 추가
- 핵심 내용
- 질문
[CD-84]: https://cd-carpe-diem.atlassian.net/browse/CD-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 단일 페이지 상세정보 GET API

---

src/api/card.ts
src/services/card.ts

(PR | ISSUE) : #8 #9 #10  [CD-30]
- 단일 카드 페이지 DELETE API 구현
- 단일 페이지 수정 API 추가
- 핵심 내용
- 질문
[CD-30]: https://cd-carpe-diem.atlassian.net/browse/CD-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 단일 페이지 삭제 DELETE API

---

src/api/card.ts
src/common/constant/responseMessage.ts
src/services/card.ts

(PR | ISSUE) : [CD-28]
- 단일 페이지 타이틀 수정 PUT API
- 작업 예정
- 핵심 내용
- 질문
[CD-28]: https://cd-carpe-diem.atlassian.net/browse/CD-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 단일 페이지 타이틀 수정 PUT API

---

src/api/card.ts
src/app.ts
src/docs/api/card/card.ts
src/services/card.ts

(PR | ISSUE) : #14  [CD-28]
- Fix: 단일 페이지 타이틀 수정 PUT API
- 작업 예정
- 핵심 내용
- 질문
[CD-28]: https://cd-carpe-diem.atlassian.net/browse/CD-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: 단일 페이지 타이틀 수정 PUT API

---

src/lambda/makeThumbnail.py

(PR | ISSUE) : #16 [CD-80]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-80]: https://cd-carpe-diem.atlassian.net/browse/CD-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge from Feat/CD-80 to develop #16

---

src/api/card.ts
src/app.ts
src/loaders/express.ts

(PR | ISSUE) : #13 
- 기존 단일 페이지 타이틀 삭제 DELETE API(#13)에서 클라이언트가 삭제를 요청하는 경우 보안상 문제 발생
- cors 허용으로 문제 해결했습니다
- 작업 예정
- 핵심 내용
- 질문

Fix: 단일 페이지 삭제 DELETE API

---

src/api/camera.ts
src/common/constant/responseMessage.ts
src/loaders/multer.ts
src/models/Expression.ts
src/models/Usim.ts
src/services/camera.ts

(PR | ISSUE) : [CD-91]
- 사용자 이미지 로드하는 API 추가했습니다.
- 클라이언트 이미지 로드 부분 구현 예정
- 스웨거 붙일 예정
- 핵심 내용
- 질문
[CD-91]: https://cd-carpe-diem.atlassian.net/browse/CD-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 사용자 이미지 GET API 추가

---

src/api/album.ts
src/api/card.ts
src/app.ts
src/common/constant/responseMessage.ts
src/services/album.ts
src/services/card.ts

(PR | ISSUE) : [CD-101]
- 앨범 전체 리스트 GET API
- Swagger는 작업 예정입니다.
- 핵심 내용
- 질문
[CD-101]: https://cd-carpe-diem.atlassian.net/browse/CD-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 앨범 리스트 GET API

---

src/api/album.ts
src/services/album.ts

(PR | ISSUE) : [CD-25]
* 단일 앨범 로드 GET API 추가
* 단일 앨범 삭제 DELETE API 추가
* 단일 앨범 로드 Swagger 적용 [CD-93]
- 핵심 내용
- 질문
[CD-25]: https://cd-carpe-diem.atlassian.net/browse/CD-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-93]: https://cd-carpe-diem.atlassian.net/browse/CD-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 앨범 로드 GET API

---

src/api/album.ts
src/services/album.ts

(PR | ISSUE) : [CD-29]
* 단일 앨범 삭제 DELETE API 추가
* 단일 앨범 삭제 Swagger 적용 [CD-92]
- 핵심 내용
- 질문
[CD-29]: https://cd-carpe-diem.atlassian.net/browse/CD-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-92]: https://cd-carpe-diem.atlassian.net/browse/CD-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 앨범 삭제 DELETE API

---

src/api/album.ts
src/services/album.ts

(PR | ISSUE) : #25  [CD-29]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-29]: https://cd-carpe-diem.atlassian.net/browse/CD-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge from Feat/CD-29 to develop #25

---

src/docs/api/album/album.ts
src/docs/api/album/index.ts
src/docs/api/card/card.ts
src/docs/index.ts

(PR | ISSUE) : [CD-93]
- 단일 앨범 GET API 명세 작성(Swagger)🫡
- 테스트 진행 완료
- 단일 앨범 DELETE API 명세 작성(Swagger)
- 테스트 진행 예정
- @XxoSio Swagger - Card API [DELETE, PUT] response desciption 이 잘못 기입되어 있는 것 같아 수정했습니다. 확인부탁드려용🫡
- 질문
[CD-93]: https://cd-carpe-diem.atlassian.net/browse/CD-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

앨범 로드 GET API Swagger 적용

---

src/docs/api/album/album.ts
src/docs/api/album/index.ts
src/docs/api/card/card.ts
src/docs/index.ts

(PR | ISSUE) : #27  [CD-93]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-93]: https://cd-carpe-diem.atlassian.net/browse/CD-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge from Feat/CD-29 to develop #27

---

src/docs/api/album/album.ts
src/docs/api/album/index.ts
src/docs/api/card/card.ts
src/docs/index.ts

(PR | ISSUE) : [CD-92]
- 단일 앨범 GET API 명세 작성(Swagger)
- 테스트 진행 완료
- 작업 예정
- 핵심 내용
- 질문
[CD-92]: https://cd-carpe-diem.atlassian.net/browse/CD-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

앨범 삭제 DELETE API Swagger 적용

---

src/api/album.ts
src/api/card.ts
src/services/album.ts

(PR | ISSUE) : #27 #28  [CD-94]
- 앨범 페이지 타이틀 수정 PUT API
- 작업 예정
- 핵심 내용
- 질문
[CD-94]: https://cd-carpe-diem.atlassian.net/browse/CD-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 앨범 타이틀 수정 PUT API

---

src/api/camera.ts
src/common/constant/responseMessage.ts
src/loaders/swagger.ts
src/models/Expression.ts
src/models/index.ts
src/services/camera.ts

(PR | ISSUE) : [CD-101]
- 웹캠 페이지 최근 저장한 영상 리스트 로드 API 구현
- expression DB thumbnail URL data 추가
- 작업 예정
- 핵심 내용
- 질문
[CD-101]: https://cd-carpe-diem.atlassian.net/browse/CD-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 최근 저장한 영상 정보 로드

---

src/api/album.ts
src/docs/api/album/album.ts
src/services/album.ts
src/services/camera.ts

(PR | ISSUE) : [CD-22]  [CD-107]
- 기존 `album -> cardId` json 데이터로 되어있던 부분 array로 바꿨습니다.
- 기존 : cardId만 띄움 -> 현재 : cardId에 따른 card 정보 띄움
- 스웨거도 적용 완료
- 작업 예정
- 핵심 내용
- 질문
[CD-22]: https://cd-carpe-diem.atlassian.net/browse/CD-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-107]: https://cd-carpe-diem.atlassian.net/browse/CD-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change: 단일 앨범 로드 API 수정

---

package.json
src/api/album.ts
src/common/constant/responseMessage.ts
src/docs/api/album/album.ts
src/models/Album.ts
src/services/album.ts

(PR | ISSUE) : [CD-109] [CD-110] ... 잔재,, [CD-43]
- 배포용 `package.json` 스크립트 변경
- 사용자 선택 카드에 따른 앨범 생성 API
- 스웨거 오류들 해결
- 핵심 내용
- 질문
[CD-109]: https://cd-carpe-diem.atlassian.net/browse/CD-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-110]: https://cd-carpe-diem.atlassian.net/browse/CD-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-43]: https://cd-carpe-diem.atlassian.net/browse/CD-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 사용자 앨범 생성 API 완료

---

.dockerignore
Dockerfile
package.json

(PR | ISSUE) : [CD-43]
- github actions 설정 CI/CD
- Dockerfile, .dockerignore 추가
- package.json - build 부분 수정
- Merge 후에 github actions - workflow 테스트 예정
- 현재 Dockerfile 이 없다는 오류로 테스트 진행이 불가해 머지를 진행함
현재 프로젝트에 영향가는 부분은 크게 없어서 머지 바로 진행하겠습니다.
- 질문
[CD-43]: https://cd-carpe-diem.atlassian.net/browse/CD-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CI/CD] GithubActions & Docker 적용

---

src/api/user.ts
src/app.ts
src/common/constant/responseMessage.ts
src/docs/api/user/index.ts
src/docs/api/user/user.ts
src/docs/index.ts
src/models/User.ts
src/services/user.ts

(PR | ISSUE) : [CD-113] [CD-114]
- 회원 정보 로드 API
- 회원 정보 수정 API
- 회원 프로필 정보 추가
- 핵심 내용
- 질문
[CD-113]: https://cd-carpe-diem.atlassian.net/browse/CD-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-114]: https://cd-carpe-diem.atlassian.net/browse/CD-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 회원 정보 로드, 회원 정보 수정 API

---

src/api/card.ts
src/docs/api/card/card.ts

(PR | ISSUE) : [CD-116]
* 로그인이 완료된 사용자만 이용 가능하도록 수정
* Request
* GET - 카드 전체 조회: /card/
* GET - 단일 카드 조회: /card/:cardId
* DELETE - 단일 카드 삭제: /card/:cardId
* PUT - 단일 카드 수정: /card/:cardId
* Swagger API 수정
* API 테스트 완료
* Swagger API 테스트
* 클라이언트, 서버(postman) 테스트
* Album API [CRUD] 수정 예정
* Swagger 적용 및 테스트 예정
- 핵심 내용
- 질문
[CD-116]: https://cd-carpe-diem.atlassian.net/browse/CD-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[RUD] Card API 로그인 이후 서비스 이용 가능하도록 수정

---

src/api/card.ts
src/docs/api/card/card.ts

(PR | ISSUE) : #44 [CD-116]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-116]: https://cd-carpe-diem.atlassian.net/browse/CD-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge from Feat/CD-116 to develop #44

---

src/api/friend.ts
src/app.ts
src/common/constant/responseMessage.ts
src/config/passport/googleAuth.ts
src/models/Friend.ts
src/models/User.ts
src/models/index.ts
src/services/auth.ts
src/services/friend.ts

(PR | ISSUE) : #43  [CD-118]
- 친구 목록 조회 GET API 제작
- user DB 프로필 사진 column 추가
- 친구 DB model 추가
- 친구 검색 API
- 친구 삭제 API
- 친구 요청
- 보낸 친구 요청 API
- 받은 친구 요청
- 친구 추가 API
- Friend DB와 Friend Request DB의 join
- 친구 요청 거절 API
- User DB와 Friend DB의 join
- 질문
[CD-118]: https://cd-carpe-diem.atlassian.net/browse/CD-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 목록 조회 GET API

---

src/api/user.ts
src/docs/api/user/user.ts

(PR | ISSUE) : #47 [CD-122]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-122]: https://cd-carpe-diem.atlassian.net/browse/CD-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge from Feat/CD-122 to develop #47

---

src/api/user.ts
src/common/constant/responseMessage.ts
src/services/user.ts

(PR | ISSUE) : #46 #47  [CD-120]
- 친구 이메일 검색 API 제작
- 친구 삭제 API
- 친구 요청
- 보낸 친구 요청 API
- 받은 친구 요청
- 친구 추가 API
- Friend DB와 Friend Request DB의 join
- 친구 요청 거절 API
- 핵심 내용
- 질문
[CD-120]: https://cd-carpe-diem.atlassian.net/browse/CD-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 검색 GET API

---

src/api/card.ts
src/api/friend.ts
src/services/friend.ts

(PR | ISSUE) : #46 #47 #49  [CD-123]
- 친구 삭제 DELETE API 제작
- 친구 요청
- 보낸 친구 요청 API
- 받은 친구 요청(JOIN)
- 친구 추가 API
- 친구 요청 거절 API
- 핵심 내용
- 질문
[CD-123]: https://cd-carpe-diem.atlassian.net/browse/CD-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 삭제 DELETE API

---

src/api/friend.ts
src/api/user.ts
src/common/constant/responseMessage.ts
src/services/user.ts

(PR | ISSUE) : #46 #47 #49 #50 #51 [CD-125]
- 친구 검색 url 수정
- 모든 유저 목록 불러오기 API 제작
- 친구 요청(JOIN)
- 받은 친구 요청
- 친구 추가 API
- 친구 요청 거절 API
- 핵심 내용
- 질문
[CD-125]: https://cd-carpe-diem.atlassian.net/browse/CD-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 모든 유저 불러오기 GET API

---

src/api/friend.ts
src/common/constant/responseMessage.ts
src/services/friend.ts

(PR | ISSUE) : #46 #47 #49 #50 #51 #52 [CD-126]
- 친구 요청 보내기 CREATE API 제작
- 작업 예정
- 친구 요청(JOIN)
- 받은 친구 요청
- 친구 추가 수락 API
- 친구 요청 거절 API
- 핵심 내용
- 질문
[CD-126]: https://cd-carpe-diem.atlassian.net/browse/CD-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 요청 보내기 CREATE API

---

src/api/friend.ts
src/common/constant/responseMessage.ts
src/models/Friend.ts
src/services/friend.ts

(PR | ISSUE) : #46 #47 #49 #50 #51 #52 #53 [CD-127]
- 친구 요청
- 받은 친구 요청
- 친구 추가 수락 API 제작
- 친구 요청 거절 API 제작
- 제작한 API Swagger 작업
- check를 사용하여 하나의 url에서 처리함
- 질문
[CD-127]: https://cd-carpe-diem.atlassian.net/browse/CD-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 요청 수락 & 거절 CREATE & DELETE API

---

src/api/album.ts
src/docs/api/album/album.ts

(PR | ISSUE) : #56  [CD-129]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-129]: https://cd-carpe-diem.atlassian.net/browse/CD-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge from Change/CD-129 to develop #56

---

src/api/friend.ts
src/common/constant/responseMessage.ts
src/services/friend.ts

(PR | ISSUE) : #51 #54 [CD-128]
- 받은 친구 요청 목록 API 제작
- 친구 거절 & 삭제 PR 제작중 잘못 수정된 부분(보낸 친구 목록 API 부분) 코드 수정
- 오타 수정
- 제작한 API들 Swagger 작업
- 핵심 내용
- 질문
[CD-128]: https://cd-carpe-diem.atlassian.net/browse/CD-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 받은 친구 요청 목록 API

---

src/api/user.ts
src/config/passport/index.ts
src/docs/api/album/album.ts
src/docs/api/friend/friend.ts
src/docs/api/friend/index.ts
src/docs/api/user/user.ts
src/docs/index.ts
src/services/album.ts
src/services/auth.ts
src/services/camera.ts
src/services/card.ts
src/services/friend.ts
src/services/user.ts

(PR | ISSUE) : #46 #49 #50 #51 #52 #53 #54 #55 [CD-140]
- Fix : 로거 디테일 정보 추가
- Fix : albumDto 속성 추가 및 스웨거 수정
- 썸네일 추가 코드 작성
-  해당 부분 swagger 수정
- Feat: 친구 API들 swagger 작업
- 친구 요청 검색 url 수정
- 작업 예정
- 친구 요청 수락 & 거절
- 실제(FE) : 같은 주소에서 check를 사용하여 검사
- swagger : 같은 주소에서 2개를 처리해야 하므로 강제로 주소값에 1, 2를  고정하여 처리
- 질문
[CD-140]: https://cd-carpe-diem.atlassian.net/browse/CD-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 API들 swagger 작업

---

src/api/album.ts
src/api/friend.ts
src/common/constant/responseMessage.ts
src/models/Album.ts
src/services/album.ts
src/services/friend.ts

(PR | ISSUE) : #61 [CD-141] [CD-142]
- 앨범 모델에 show_check 추가
- 내 앨범 권한 설정 PUT API 제작
- 친구 앨범 확인 GET API 제작
- FE에서 동작 테스트 예정
- 친구 요청 코드 수정
- 이미 친구가 되어있거나, 상대방이 친구 요청을 보낸 경우 요청이 불가능하도록 수정 예정
- 친구 앨범 확인 API swagger 작업 예정
- 핵심 내용
- 질문
[CD-141]: https://cd-carpe-diem.atlassian.net/browse/CD-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CD-142]: https://cd-carpe-diem.atlassian.net/browse/CD-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 친구 앨범 확인 GET API

---

src/api/album.ts
src/api/card.ts
src/app.ts
src/services/album.ts
src/services/card.ts

(PR | ISSUE) : [CD-139]
- 무한 스크롤 앨범 API 추가
- 작업 예정
- 핵심 내용
- 질문
[CD-139]: https://cd-carpe-diem.atlassian.net/browse/CD-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 페이지네이션-앨범(무한 스크롤 추가) API

---

src/api/friendAlbum.ts
src/app.ts
src/services/friendAlbum.ts

(PR | ISSUE) : [CD-163]
- 작업 내용
- 작업 예정
- 핵심 내용
- 질문
[CD-163]: https://cd-carpe-diem.atlassian.net/browse/CD-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: API 수정 및 포트 변경

---

src/models/index.ts

(PR | ISSUE) : [CD-164]
- 현재 시간이 아닌 UTC 시간으로 표시되는 오류 수정
- 작업 예정
- 핵심 내용
- 질문
[CD-164]: https://cd-carpe-diem.atlassian.net/browse/CD-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: UTC로 표시되는 시간 수정(DB)

---

package.json
src/api/mail.ts
src/app.ts
src/config/index.ts
src/loaders/mail.ts
src/services/camera.ts

(ISSUE) : [CD-170]
- 메일 모듈, 메일 api 추가했습니다.
- 그래프 이미지 추출, 메일 보내기
- 핵심 내용
- 질문
[CD-170]: https://cd-carpe-diem.atlassian.net/browse/CD-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: 메일 알림

---

src/api/report.ts
src/app.ts
src/common/constant/responseMessage.ts
src/services/report.ts

(PR | ISSUE) : #{PR번호} [CD-{이슈번호}]
- 최근 일주일 내 감정 통계 결과 GET API 구현
- request
- `GET /report` 
- response
```json
{
"2023-02-26": {
"happy": 0,
"sad": 0,
"surprised": 0,
"disgusted": 0,
"angry": 0,
"fearful": 0
},
"2023-02-27": {
"happy": 0,
"sad": 0,
"surprised": 0,
"disgusted": 0,
"angry": 0,
"fearful": 0
},
"2023-02-28": {
"happy": 1,
"sad": 0,
"surprised": 0,
"disgusted": 0,
"angry": 0,
"fearful": 0
},
"2023-03-01": {
"happy": 0,
"sad": 0,
"surprised": 0,
"disgusted": 0,
"angry": 1,
"fearful": 0
},
"2023-03-02": {
"happy": 4,
"sad": 1,
"surprised": 1,
"disgusted": 0,
"angry": 0,
"fearful": 0
},
"2023-03-03": {
"happy": 0,
"sad": 0,
"surprised": 0,
"disgusted": 0,
"angry": 0,
"fearful": 0
},
"2023-03-04": {
"happy": 0,
"sad": 1,
"surprised": 0,
"disgusted": 1,
"angry": 0,
"fearful": 0
} …
```

Feat: 감정 리포트 추가

---

src/models/index.ts

(PR | ISSUE) : #73  [CD-171]
- 썸네일 저장 시간과 최근 저장 영상 출력 시간 수정
- 작업 예정
- 핵심 내용
- 질문
[CD-171]: https://cd-carpe-diem.atlassian.net/browse/CD-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: 시간 수정

---

src/loaders/multer.ts
src/services/report.ts

(PR | ISSUE) : #{PR번호} [CD-{이슈번호}]
- 시간 저장 오류 수정
- 감정 리포트 일주일 로드 오류 수정
- 작업 예정
- 핵심 내용
- 질문

Fix: 시간 관련 오류들 수정
